export const en = {
  home: "Home",
  back: "Back",
  close: "Close",
  cancel: "Cancel",
  next: "Next round",
  finish: "Final scores",
  bank: "Bank",
  "top-ten": "Top Ten",
  tagline: "A little knowledge. A lot of good company.",
  welcome: "Make it a game night.",
  pick: "Two teams. One phone. Pick your game.",
  bankDesc:
    "Keep the answers coming. Three strikes, and the other team can steal the round.",
  topDesc:
    "Ten hidden answers. The deeper you dig, the more points you take home.",
  bankRule: "3 strikes · 1 point per round",
  topRule: "10 answers · 55 points to play for",
  playBank: "Play Bank",
  playTop: "Play Top Ten",
  how: "How to play",
  onePhone: "One phone",
  twoTeams: "Two teams",
  noAccount: "Just play",
  packs: "Topic packs",
  packsDesc: "Make the next round your own.",
  browse: "Explore topics",
  resume: "Pick up where you left off",
  resumeGame: "Resume game",
  savedRound: "Round {round} of {total}",
  rulesTitle: "Your phone. Your game show.",
  rulesIntro:
    "Choose one person to host. Split everyone else into two teams. The host reads the question and judges the answers.",
  bankRules:
    "The starting team answers from one shared pool. A wrong answer adds a strike. At three strikes, the other team gets one steal attempt. The host decides: a successful steal wins the round; a failed steal gives it to the original team. Clearing every answer also wins the round. Each round is worth 1 point. Starting teams alternate each round.",
  topRules:
    "The teams take turns guessing the hidden list. The host confirms each answer, reveals it and awards its rank in points: rank 1 = 1, rank 10 = 10. Correct answers and passes switch teams. An answer scores only once. The host can change the active team and end a round early. Each full list is worth 55 points.",
  hostNote:
    "Use Undo for a mistaken tap. Hide the answer key before showing or mirroring the phone. An answer key shown on the phone is also visible on a mirrored TV.",
  houseNote:
    "House lists are our own selections and subjective rankings. Factual lists show their definition and source.",
  setupTitle: "Set the table.",
  setupDesc: "Name your teams and choose a topic for each round.",
  yourTeams: "Your teams",
  team1: "Team 1",
  team2: "Team 2",
  rounds: "Rounds",
  chooseRounds: "Number of rounds",
  roundTopics: "Tonight’s lineup",
  selectedCount: "{count} of {total} topics selected",
  selectTopics: "Choose {count} more topics",
  ready: "Your game is ready",
  start: "Start game",
  round: "Round",
  chooseTopic: "Choose a topic",
  replace: "Change topic",
  remove: "Remove",
  searchTopics: "Search topics",
  readyPacks: "Ready to play",
  allTopics: "All topics",
  custom: "Custom topic",
  makePack: "Create a pack",
  noResults: "No matching topics. Try another search or create your own.",
  selected: "Selected",
  available: "Ready",
  createFor: "Create for this topic",
  preview: "Preview pack",
  factual: "Factual list",
  house: "House list",
  source: "Source & context",
  checked: "Checked",
  libraryTitle: "Your next great round.",
  libraryDesc:
    "Play a ready-made pack, or bring a topic only your friends would know.",
  customTitle: "Your topic. Your rules.",
  customDesc:
    "Create a pack with your AI assistant, then bring it back here. No API or subscription is required by this game.",
  topicLabel: "What is your topic?",
  topicPlaceholder: "e.g. Famous Formula 1 drivers",
  gameLabel: "Game",
  step1: "1. Copy your request",
  step1Desc:
    "Paste this request into the AI assistant you already use. Ask it to return the completed JSON.",
  copyPrompt: "Copy request",
  copied: "Copied",
  copyFailed: "Select the request below and copy it manually.",
  step2: "2. Bring your pack back",
  step2Desc:
    "Paste the returned JSON or choose a .json file. We check its structure; you review the facts and wording.",
  jsonLabel: "Your pack JSON",
  fileLabel: "Choose JSON file",
  validate: "Check & preview",
  invalidPack: "This pack needs a few fixes.",
  review: "Review before adding",
  reviewConfirm: "I have reviewed the answers, Arabic wording and sources.",
  addPack: "Add to my topics",
  imported: "Your pack is ready to play.",
  duplicatePack: "A pack with this ID already exists. Use a new unique ID.",
  customId: "Custom pack IDs must start with custom-.",
  capacity: "Your library is full. Remove a custom pack before adding another.",
  deviceOnly:
    "Custom packs and saved games stay in this browser. Export your packs to keep a backup.",
  download: "Export JSON",
  deletePack: "Delete pack",
  deleteConfirm:
    "Remove this custom pack from this browser? An active game using it will keep its own copy.",
  delete: "Delete",
  hostKey: "Host answer key",
  showKey: "Show answer key",
  hideKey: "Hide answer key",
  keyWarning:
    "Host only: showing this reveals every answer, including on a mirrored TV.",
  reveal: "Confirm answer",
  found: "Found",
  answersFound: "{count} / {total} answers found",
  answerInput: "Check a spoken answer",
  answerPlaceholder: "Type an answer…",
  checkAnswer: "Check answer",
  noMatch:
    "No exact match. Open the host key to check manually; the host has the final say.",
  alreadyFound: "This answer has already been found.",
  answerMatched: "Match found. Confirm to reveal and award it.",
  currentTurn: "It’s {team}’s turn",
  selectTeam: "Give the turn to {team}",
  strikes: "Strikes",
  wrong: "Wrong answer",
  stealTime: "Time to steal.",
  stealDesc: "{team} gets one attempt. The host decides the outcome.",
  stealSuccess: "Steal successful",
  stealFailed: "Steal failed",
  undo: "Undo",
  pass: "Wrong / pass",
  endRound: "End round",
  endRoundTitle: "Finish this round?",
  bankEndDesc: "Choose the round winner. They receive 1 point.",
  topEndDesc:
    "Keep the points earned so far. Hidden answers receive no points.",
  awardTo: "Award to {team}",
  roundComplete: "Round complete",
  roundWon: "{team} banks the round!",
  point: "pt",
  points: "pts",
  nextTopic: "Up next",
  viewAnswers: "See the full answer list",
  gameFinished: "That’s a wrap.",
  winner: "{team} wins!",
  draw: "A perfect tie.",
  finalScore: "Final score",
  playAgain: "Play again",
  newGame: "Choose another game",
  roundRecap: "The round-by-round",
  exit: "Leave game",
  exitTitle: "Take a break?",
  exitDesc: "Your game is saved on this browser. You can resume from Home.",
  leave: "Save & go home",
  newConfirm: "Start a new game?",
  newDesc:
    "This replaces your saved game. Custom topic packs stay in your library.",
  newStart: "Start new game",
  storageFailed:
    "This browser could not save your data. You can keep playing, but a refresh may lose progress. Export custom packs as a backup.",
  scoreAnnounce: "{first}: {a}. {second}: {b}.",
  restartError: "Something interrupted the game.",
  reload: "Reload",
  skip: "Skip to game",
  roundPoint: "+1 round point",
  chooseDifferent: "Choose a different topic for each round.",
  topicLimit: "All round slots are full. Remove or change a topic first.",
  ranking: "Rank = points",
  blankTeams: "Enter a name for each team.",
  packCount: "{count} packs",
  rules: "Rules",
};
export type TranslationKey = keyof typeof en;
export const ar: Record<TranslationKey, string> = {
  home: "الرئيسية",
  back: "رجوع",
  close: "إغلاق",
  cancel: "إلغاء",
  next: "الجولة التالية",
  finish: "النتيجة النهائية",
  bank: "البنك",
  "top-ten": "توب تن",
  tagline: "معلومات تجمعنا… ووناسة تكمل ليلتنا.",
  welcome: "خلّها ليلة لعب.",
  pick: "فريقان. هاتف واحد. اختر لعبتك.",
  bankDesc:
    "واصل الإجابات الصحيحة. بعد ثلاثة أخطاء، يحصل الفريق الآخر على فرصة لخطف الجولة.",
  topDesc: "عشر إجابات مخفية. كلما اكتشفت مرتبة أعلى رقماً، جمعت نقاطاً أكثر.",
  bankRule: "3 أخطاء · نقطة لكل جولة",
  topRule: "10 إجابات · 55 نقطة في كل قائمة",
  playBank: "العب البنك",
  playTop: "العب توب تن",
  how: "طريقة اللعب",
  onePhone: "هاتف واحد",
  twoTeams: "فريقان",
  noAccount: "ابدأ واستمتع",
  packs: "حزم المواضيع",
  packsDesc: "خلّ الجولة القادمة على ذوقك.",
  browse: "تصفّح المواضيع",
  resume: "كمّل من حيث توقفت",
  resumeGame: "متابعة اللعب",
  savedRound: "الجولة {round} من {total}",
  rulesTitle: "هاتفك يصير برنامج مسابقات.",
  rulesIntro:
    "اختاروا مقدّماً للعبة، وانقسموا إلى فريقين. يقرأ المقدّم السؤال ويحكم على الإجابات.",
  bankRules:
    "يجيب الفريق الذي يبدأ من قائمة مشتركة. كل إجابة خاطئة تضيف خطأً. بعد ثلاثة أخطاء، يحصل الفريق الآخر على محاولة واحدة لخطف الجولة. يقرر المقدّم النتيجة: نجاح الخطف يمنح الجولة للفريق الآخر، وفشله يمنحها للفريق الأصلي. اكتشاف جميع الإجابات يفوز بالجولة أيضاً. كل جولة بنقطة واحدة، ويتبادل الفريقان البداية بين الجولات.",
  topRules:
    "يتناوب الفريقان تخمين إجابات القائمة المخفية. يؤكد المقدّم الإجابة ويكشفها ويمنح نقاطاً تساوي رقم المرتبة: المرتبة 1 بنقطة، والمرتبة 10 بعشر نقاط. ينتقل الدور بعد الإجابة الصحيحة أو التمرير. لا تُحتسب الإجابة مرتين. يمكن للمقدّم تغيير الفريق صاحب الدور أو إنهاء الجولة مبكراً. مجموع نقاط القائمة الكاملة 55.",
  hostNote:
    "استخدم التراجع لتصحيح ضغطة بالخطأ. أخفِ دليل الإجابات قبل عرض الهاتف أو عكس شاشته. ما يظهر على الهاتف يظهر أيضاً على التلفاز عند عكس الشاشة.",
  houseNote:
    "القوائم المختارة من إعدادنا وترتيبها شخصي. أما القوائم المعلوماتية فتعرض تعريفها ومصدرها.",
  setupTitle: "جهّزوا الفريقين.",
  setupDesc: "سمّوا الفريقين، واختاروا موضوعاً لكل جولة.",
  yourTeams: "الفريقان",
  team1: "الفريق الأول",
  team2: "الفريق الثاني",
  rounds: "الجولات",
  chooseRounds: "عدد الجولات",
  roundTopics: "مواضيع الليلة",
  selectedCount: "تم اختيار {count} من {total} مواضيع",
  selectTopics: "اختر {count} مواضيع إضافية",
  ready: "اللعبة جاهزة",
  start: "ابدأ اللعبة",
  round: "الجولة",
  chooseTopic: "اختر موضوعاً",
  replace: "تغيير الموضوع",
  remove: "إزالة",
  searchTopics: "ابحث عن موضوع",
  readyPacks: "جاهزة للعب",
  allTopics: "كل المواضيع",
  custom: "موضوع مخصص",
  makePack: "أنشئ حزمة",
  noResults: "لا توجد مواضيع مطابقة. جرّب بحثاً آخر أو أنشئ موضوعك.",
  selected: "تم الاختيار",
  available: "جاهز",
  createFor: "أنشئ حزمة لهذا الموضوع",
  preview: "معاينة الحزمة",
  factual: "قائمة معلوماتية",
  house: "قائمة مختارة",
  source: "المصدر والتفاصيل",
  checked: "تاريخ المراجعة",
  libraryTitle: "موضوع يحمّس الجميع.",
  libraryDesc: "اختر حزمة جاهزة، أو أضف موضوعاً يعرفه أصحابك جيداً.",
  customTitle: "موضوعك… على ذوقك.",
  customDesc:
    "أنشئ حزمة بمساعدة مساعدك الذكي، ثم أضفها هنا. اللعبة لا تتطلب اشتراكاً أو اتصالاً بواجهة ذكاء اصطناعي.",
  topicLabel: "ما الموضوع الذي تريده؟",
  topicPlaceholder: "مثلاً: أشهر سائقي فورمولا 1",
  gameLabel: "اللعبة",
  step1: "1. انسخ طلبك",
  step1Desc:
    "ألصق هذا الطلب في المساعد الذكي الذي تستخدمه، واطلب منه إرجاع ملف JSON مكتمل.",
  copyPrompt: "انسخ الطلب",
  copied: "تم النسخ",
  copyFailed: "حدّد الطلب أدناه وانسخه يدوياً.",
  step2: "2. أضف الحزمة",
  step2Desc:
    "ألصق JSON الناتج أو اختر ملفاً بصيغة .json. نتحقق من البنية، وأنت تراجع المعلومات والصياغة.",
  jsonLabel: "بيانات الحزمة بصيغة JSON",
  fileLabel: "اختر ملف JSON",
  validate: "تحقق وعاين",
  invalidPack: "تحتاج هذه الحزمة إلى بعض التصحيحات.",
  review: "راجع قبل الإضافة",
  reviewConfirm: "راجعت الإجابات والصياغة العربية والمصادر.",
  addPack: "أضف إلى مواضيعي",
  imported: "حزمتك جاهزة للعب.",
  duplicatePack: "توجد حزمة بهذا المعرّف. استخدم معرّفاً جديداً.",
  customId: "يجب أن يبدأ معرّف الحزمة المخصصة بـ custom-.",
  capacity: "مكتبتك ممتلئة. احذف حزمة مخصصة قبل إضافة أخرى.",
  deviceOnly:
    "تُحفظ الحزم المخصصة والألعاب في هذا المتصفح فقط. صدّر حزمك للاحتفاظ بنسخة احتياطية.",
  download: "تصدير JSON",
  deletePack: "حذف الحزمة",
  deleteConfirm:
    "حذف هذه الحزمة المخصصة من المتصفح؟ ستحتفظ اللعبة الجارية بنسختها الخاصة.",
  delete: "حذف",
  hostKey: "دليل إجابات المقدّم",
  showKey: "إظهار دليل الإجابات",
  hideKey: "إخفاء دليل الإجابات",
  keyWarning:
    "للمقدّم فقط: ستظهر كل الإجابات، بما في ذلك على التلفاز عند عكس الشاشة.",
  reveal: "تأكيد الإجابة",
  found: "تم اكتشافها",
  answersFound: "تم اكتشاف {count} من {total} إجابات",
  answerInput: "تحقق من إجابة مسموعة",
  answerPlaceholder: "اكتب الإجابة…",
  checkAnswer: "تحقق",
  noMatch:
    "لا توجد مطابقة تامة. افتح دليل الإجابات للتحقق يدوياً؛ القرار النهائي للمقدّم.",
  alreadyFound: "تم اكتشاف هذه الإجابة مسبقاً.",
  answerMatched: "وُجدت إجابة مطابقة. أكّد لكشفها واحتسابها.",
  currentTurn: "الدور على {team}",
  selectTeam: "امنح الدور إلى {team}",
  strikes: "الأخطاء",
  wrong: "إجابة خاطئة",
  stealTime: "فرصة لخطف الجولة.",
  stealDesc: "أمام {team} محاولة واحدة. المقدّم يقرر النتيجة.",
  stealSuccess: "نجح الخطف",
  stealFailed: "فشل الخطف",
  undo: "تراجع",
  pass: "خطأ / تمرير",
  endRound: "إنهاء الجولة",
  endRoundTitle: "إنهاء هذه الجولة؟",
  bankEndDesc: "اختر الفريق الفائز بالجولة ليحصل على نقطة واحدة.",
  topEndDesc: "تُحفظ النقاط المكتسبة. الإجابات المخفية لا تُحتسب.",
  awardTo: "امنح الجولة إلى {team}",
  roundComplete: "اكتملت الجولة",
  roundWon: "{team} يفوز بالجولة!",
  point: "نقطة",
  points: "نقاط",
  nextTopic: "الموضوع التالي",
  viewAnswers: "عرض قائمة الإجابات الكاملة",
  gameFinished: "انتهت اللعبة.",
  winner: "الفائز: {team}!",
  draw: "تعادل جميل.",
  finalScore: "النتيجة النهائية",
  playAgain: "إعادة اللعب",
  newGame: "اختر لعبة أخرى",
  roundRecap: "نتائج الجولات",
  exit: "مغادرة اللعبة",
  exitTitle: "وقت الاستراحة؟",
  exitDesc: "لعبتك محفوظة في هذا المتصفح. يمكنك متابعتها من الرئيسية.",
  leave: "احفظ وارجع للرئيسية",
  newConfirm: "بدء لعبة جديدة؟",
  newDesc: "ستحل هذه اللعبة محل لعبتك المحفوظة. تبقى حزمك المخصصة في المكتبة.",
  newStart: "ابدأ لعبة جديدة",
  storageFailed:
    "تعذّر حفظ البيانات في هذا المتصفح. يمكنك مواصلة اللعب، لكن تحديث الصفحة قد يفقدك التقدم. صدّر حزمك المخصصة للاحتفاظ بها.",
  scoreAnnounce: "{first}: {a}. {second}: {b}.",
  restartError: "حدثت مشكلة أثناء اللعب.",
  reload: "أعد التحميل",
  skip: "انتقل إلى اللعبة",
  roundPoint: "+1 نقطة للجولة",
  chooseDifferent: "اختر موضوعاً مختلفاً لكل جولة.",
  topicLimit: "اكتملت مواضيع الجولات. أزل موضوعاً أو غيّره أولاً.",
  ranking: "رقم المرتبة = النقاط",
  blankTeams: "اكتب اسماً لكل فريق.",
  packCount: "{count} حزم",
  rules: "القواعد",
};
